// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sadSumScale2 (
        ap_ready,
        sum_0_V_read,
        sum_1_V_read,
        sum_2_V_read,
        sum_3_V_read,
        sum_4_V_read,
        sum_5_V_read,
        sum_6_V_read,
        ap_return
);


output   ap_ready;
input  [4:0] sum_0_V_read;
input  [4:0] sum_1_V_read;
input  [4:0] sum_2_V_read;
input  [4:0] sum_3_V_read;
input  [4:0] sum_4_V_read;
input  [4:0] sum_5_V_read;
input  [4:0] sum_6_V_read;
output  [6:0] ap_return;

wire   [3:0] tmp_5_fu_72_p1;
wire   [0:0] tmp_4_fu_64_p3;
wire   [3:0] sum_V_cast_fu_76_p2;
wire   [3:0] sum_0_V_write_assig_fu_82_p3;
wire   [3:0] tmp_7_fu_102_p1;
wire   [0:0] tmp_6_fu_94_p3;
wire   [3:0] sum_V_1_cast_fu_106_p2;
wire   [3:0] sum_1_V_write_assig_fu_112_p3;
wire   [4:0] sum_0_V_write_assig_1_fu_90_p1;
wire   [4:0] sum_1_V_write_assig_1_fu_120_p1;
wire   [4:0] tmp_V_1_fu_124_p2;
wire   [3:0] tmp_9_fu_142_p1;
wire   [0:0] tmp_8_fu_134_p3;
wire   [3:0] sum_V_2_cast_fu_146_p2;
wire   [3:0] sum_2_V_write_assig_fu_152_p3;
wire   [3:0] tmp_11_fu_172_p1;
wire   [0:0] tmp_10_fu_164_p3;
wire   [3:0] sum_V_3_cast_fu_176_p2;
wire   [3:0] sum_3_V_write_assig_fu_182_p3;
wire   [4:0] sum_2_V_write_assig_1_fu_160_p1;
wire   [4:0] sum_3_V_write_assig_1_fu_190_p1;
wire   [4:0] tmp_fu_194_p2;
wire   [5:0] tmp_cast_fu_200_p1;
wire   [5:0] tmp_V_1_cast4_fu_130_p1;
wire   [5:0] tmp_V_3_fu_204_p2;
wire   [3:0] tmp_13_fu_222_p1;
wire   [0:0] tmp_12_fu_214_p3;
wire   [3:0] sum_V_4_cast_fu_226_p2;
wire   [3:0] sum_4_V_write_assig_fu_232_p3;
wire   [3:0] tmp_15_fu_252_p1;
wire   [0:0] tmp_14_fu_244_p3;
wire   [3:0] sum_V_5_cast_fu_256_p2;
wire   [3:0] sum_5_V_write_assig_fu_262_p3;
wire   [3:0] tmp_17_fu_282_p1;
wire   [0:0] tmp_16_fu_274_p3;
wire   [3:0] sum_V_6_cast_fu_286_p2;
wire   [3:0] sum_6_V_write_assig_fu_292_p3;
wire   [6:0] tmp_V_3_cast3_fu_210_p1;
wire   [6:0] tmp_3_4_cast_cast_fu_240_p1;
wire   [4:0] sum_5_V_write_assig_1_fu_270_p1;
wire   [4:0] sum_6_V_write_assig_1_fu_300_p1;
wire   [4:0] tmp2_fu_310_p2;
wire   [6:0] tmp2_cast_fu_316_p1;
wire   [6:0] tmp1_fu_304_p2;

assign ap_ready = 1'b1;

assign ap_return = (tmp2_cast_fu_316_p1 + tmp1_fu_304_p2);

assign sum_0_V_write_assig_1_fu_90_p1 = sum_0_V_write_assig_fu_82_p3;

assign sum_0_V_write_assig_fu_82_p3 = ((tmp_4_fu_64_p3[0:0] === 1'b1) ? sum_V_cast_fu_76_p2 : tmp_5_fu_72_p1);

assign sum_1_V_write_assig_1_fu_120_p1 = sum_1_V_write_assig_fu_112_p3;

assign sum_1_V_write_assig_fu_112_p3 = ((tmp_6_fu_94_p3[0:0] === 1'b1) ? sum_V_1_cast_fu_106_p2 : tmp_7_fu_102_p1);

assign sum_2_V_write_assig_1_fu_160_p1 = sum_2_V_write_assig_fu_152_p3;

assign sum_2_V_write_assig_fu_152_p3 = ((tmp_8_fu_134_p3[0:0] === 1'b1) ? sum_V_2_cast_fu_146_p2 : tmp_9_fu_142_p1);

assign sum_3_V_write_assig_1_fu_190_p1 = sum_3_V_write_assig_fu_182_p3;

assign sum_3_V_write_assig_fu_182_p3 = ((tmp_10_fu_164_p3[0:0] === 1'b1) ? sum_V_3_cast_fu_176_p2 : tmp_11_fu_172_p1);

assign sum_4_V_write_assig_fu_232_p3 = ((tmp_12_fu_214_p3[0:0] === 1'b1) ? sum_V_4_cast_fu_226_p2 : tmp_13_fu_222_p1);

assign sum_5_V_write_assig_1_fu_270_p1 = sum_5_V_write_assig_fu_262_p3;

assign sum_5_V_write_assig_fu_262_p3 = ((tmp_14_fu_244_p3[0:0] === 1'b1) ? sum_V_5_cast_fu_256_p2 : tmp_15_fu_252_p1);

assign sum_6_V_write_assig_1_fu_300_p1 = sum_6_V_write_assig_fu_292_p3;

assign sum_6_V_write_assig_fu_292_p3 = ((tmp_16_fu_274_p3[0:0] === 1'b1) ? sum_V_6_cast_fu_286_p2 : tmp_17_fu_282_p1);

assign sum_V_1_cast_fu_106_p2 = (4'd0 - tmp_7_fu_102_p1);

assign sum_V_2_cast_fu_146_p2 = (4'd0 - tmp_9_fu_142_p1);

assign sum_V_3_cast_fu_176_p2 = (4'd0 - tmp_11_fu_172_p1);

assign sum_V_4_cast_fu_226_p2 = (4'd0 - tmp_13_fu_222_p1);

assign sum_V_5_cast_fu_256_p2 = (4'd0 - tmp_15_fu_252_p1);

assign sum_V_6_cast_fu_286_p2 = (4'd0 - tmp_17_fu_282_p1);

assign sum_V_cast_fu_76_p2 = (4'd0 - tmp_5_fu_72_p1);

assign tmp1_fu_304_p2 = (tmp_V_3_cast3_fu_210_p1 + tmp_3_4_cast_cast_fu_240_p1);

assign tmp2_cast_fu_316_p1 = tmp2_fu_310_p2;

assign tmp2_fu_310_p2 = (sum_5_V_write_assig_1_fu_270_p1 + sum_6_V_write_assig_1_fu_300_p1);

assign tmp_10_fu_164_p3 = sum_3_V_read[32'd4];

assign tmp_11_fu_172_p1 = sum_3_V_read[3:0];

assign tmp_12_fu_214_p3 = sum_4_V_read[32'd4];

assign tmp_13_fu_222_p1 = sum_4_V_read[3:0];

assign tmp_14_fu_244_p3 = sum_5_V_read[32'd4];

assign tmp_15_fu_252_p1 = sum_5_V_read[3:0];

assign tmp_16_fu_274_p3 = sum_6_V_read[32'd4];

assign tmp_17_fu_282_p1 = sum_6_V_read[3:0];

assign tmp_3_4_cast_cast_fu_240_p1 = sum_4_V_write_assig_fu_232_p3;

assign tmp_4_fu_64_p3 = sum_0_V_read[32'd4];

assign tmp_5_fu_72_p1 = sum_0_V_read[3:0];

assign tmp_6_fu_94_p3 = sum_1_V_read[32'd4];

assign tmp_7_fu_102_p1 = sum_1_V_read[3:0];

assign tmp_8_fu_134_p3 = sum_2_V_read[32'd4];

assign tmp_9_fu_142_p1 = sum_2_V_read[3:0];

assign tmp_V_1_cast4_fu_130_p1 = tmp_V_1_fu_124_p2;

assign tmp_V_1_fu_124_p2 = (sum_0_V_write_assig_1_fu_90_p1 + sum_1_V_write_assig_1_fu_120_p1);

assign tmp_V_3_cast3_fu_210_p1 = tmp_V_3_fu_204_p2;

assign tmp_V_3_fu_204_p2 = (tmp_cast_fu_200_p1 + tmp_V_1_cast4_fu_130_p1);

assign tmp_cast_fu_200_p1 = tmp_fu_194_p2;

assign tmp_fu_194_p2 = (sum_2_V_write_assig_1_fu_160_p1 + sum_3_V_write_assig_1_fu_190_p1);

endmodule //sadSumScale2
