// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// config
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of status_inEventsNum
//        bit 31~0 - status_inEventsNum[31:0] (Read)
// 0x14 : Data signal of status_inEventsNum
//        bit 31~0 - status_inEventsNum[63:32] (Read)
// 0x18 : Control signal of status_inEventsNum
//        bit 0  - status_inEventsNum_ap_vld (Read/COR)
//        others - reserved
// 0x1c : Data signal of status_cornerEventsNum
//        bit 31~0 - status_cornerEventsNum[31:0] (Read/Write)
// 0x20 : Data signal of status_cornerEventsNum
//        bit 31~0 - status_cornerEventsNum[63:32] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of status_durationTime
//        bit 31~0 - status_durationTime[31:0] (Read)
// 0x2c : Data signal of status_durationTime
//        bit 31~0 - status_durationTime[63:32] (Read)
// 0x30 : Control signal of status_durationTime
//        bit 0  - status_durationTime_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEVENTRATESTAT_CONFIG_ADDR_STATUS_INEVENTSNUM_DATA     0x10
#define XEVENTRATESTAT_CONFIG_BITS_STATUS_INEVENTSNUM_DATA     64
#define XEVENTRATESTAT_CONFIG_ADDR_STATUS_INEVENTSNUM_CTRL     0x18
#define XEVENTRATESTAT_CONFIG_ADDR_STATUS_CORNEREVENTSNUM_DATA 0x1c
#define XEVENTRATESTAT_CONFIG_BITS_STATUS_CORNEREVENTSNUM_DATA 64
#define XEVENTRATESTAT_CONFIG_ADDR_STATUS_DURATIONTIME_DATA    0x28
#define XEVENTRATESTAT_CONFIG_BITS_STATUS_DURATIONTIME_DATA    64
#define XEVENTRATESTAT_CONFIG_ADDR_STATUS_DURATIONTIME_CTRL    0x30

