// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xeventstreamduplicate.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEventstreamduplicate_CfgInitialize(XEventstreamduplicate *InstancePtr, XEventstreamduplicate_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_BaseAddress = ConfigPtr->Config_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEventstreamduplicate_Set_config_V(XEventstreamduplicate *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEventstreamduplicate_WriteReg(InstancePtr->Config_BaseAddress, XEVENTSTREAMDUPLICATE_CONFIG_ADDR_CONFIG_V_DATA, Data);
}

u32 XEventstreamduplicate_Get_config_V(XEventstreamduplicate *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEventstreamduplicate_ReadReg(InstancePtr->Config_BaseAddress, XEVENTSTREAMDUPLICATE_CONFIG_ADDR_CONFIG_V_DATA);
    return Data;
}

