// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="EFAST_process_data,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z045ffg900-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.723250,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=456,HLS_SYN_DSP=3,HLS_SYN_FF=5495,HLS_SYN_LUT=7564}" *)

module EFAST_process_data (
        xStreamIn_V_V_TDATA,
        yStreamIn_V_V_TDATA,
        tsStreamIn_V_V_TDATA,
        polStreamIn_V_V_TDATA,
        xStreamOut_V_V_TDATA,
        yStreamOut_V_V_TDATA,
        tsStreamOut_V_V_TDATA,
        polStreamOut_V_V_TDATA,
        isFinalCornerStream_V_V_TDATA,
        ap_clk,
        ap_rst_n,
        xStreamIn_V_V_TVALID,
        xStreamIn_V_V_TREADY,
        yStreamIn_V_V_TVALID,
        yStreamIn_V_V_TREADY,
        polStreamIn_V_V_TVALID,
        polStreamIn_V_V_TREADY,
        tsStreamIn_V_V_TVALID,
        tsStreamIn_V_V_TREADY,
        xStreamOut_V_V_TVALID,
        xStreamOut_V_V_TREADY,
        yStreamOut_V_V_TVALID,
        yStreamOut_V_V_TREADY,
        polStreamOut_V_V_TVALID,
        polStreamOut_V_V_TREADY,
        tsStreamOut_V_V_TVALID,
        tsStreamOut_V_V_TREADY,
        isFinalCornerStream_V_V_TVALID,
        isFinalCornerStream_V_V_TREADY,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);


input  [15:0] xStreamIn_V_V_TDATA;
input  [15:0] yStreamIn_V_V_TDATA;
input  [63:0] tsStreamIn_V_V_TDATA;
input  [7:0] polStreamIn_V_V_TDATA;
output  [15:0] xStreamOut_V_V_TDATA;
output  [15:0] yStreamOut_V_V_TDATA;
output  [63:0] tsStreamOut_V_V_TDATA;
output  [7:0] polStreamOut_V_V_TDATA;
output  [7:0] isFinalCornerStream_V_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   xStreamIn_V_V_TVALID;
output   xStreamIn_V_V_TREADY;
input   yStreamIn_V_V_TVALID;
output   yStreamIn_V_V_TREADY;
input   polStreamIn_V_V_TVALID;
output   polStreamIn_V_V_TREADY;
input   tsStreamIn_V_V_TVALID;
output   tsStreamIn_V_V_TREADY;
output   xStreamOut_V_V_TVALID;
input   xStreamOut_V_V_TREADY;
output   yStreamOut_V_V_TVALID;
input   yStreamOut_V_V_TREADY;
output   polStreamOut_V_V_TVALID;
input   polStreamOut_V_V_TREADY;
output   tsStreamOut_V_V_TVALID;
input   tsStreamOut_V_V_TREADY;
output   isFinalCornerStream_V_V_TVALID;
input   isFinalCornerStream_V_V_TREADY;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

reg    ap_rst_n_inv;
wire    truncateStream_U0_ap_start;
wire    truncateStream_U0_ap_done;
wire    truncateStream_U0_ap_continue;
wire    truncateStream_U0_ap_idle;
wire    truncateStream_U0_ap_ready;
wire   [95:0] truncateStream_U0_packetEventDataStrea_din;
wire    truncateStream_U0_packetEventDataStrea_write;
wire   [9:0] truncateStream_U0_xStreamOut_V_V_din;
wire    truncateStream_U0_xStreamOut_V_V_write;
wire   [9:0] truncateStream_U0_yStreamOut_V_V_din;
wire    truncateStream_U0_yStreamOut_V_V_write;
wire   [0:0] truncateStream_U0_polStreamOut_V_V_din;
wire    truncateStream_U0_polStreamOut_V_V_write;
wire   [31:0] truncateStream_U0_tsStreamOut_V_V_din;
wire    truncateStream_U0_tsStreamOut_V_V_write;
wire    truncateStream_U0_start_out;
wire    truncateStream_U0_start_write;
wire    truncateStream_U0_xStreamIn_V_V_TREADY;
wire    truncateStream_U0_yStreamIn_V_V_TREADY;
wire    truncateStream_U0_polStreamIn_V_V_TREADY;
wire    truncateStream_U0_tsStreamIn_V_V_TREADY;
reg    initStageInterleaveS_U0_ap_start;
wire    initStageInterleaveS_U0_ap_done;
wire    initStageInterleaveS_U0_ap_continue;
wire    initStageInterleaveS_U0_ap_idle;
wire    initStageInterleaveS_U0_ap_ready;
wire   [31:0] initStageInterleaveS_U0_glFeedbackCounter_out_din;
wire    initStageInterleaveS_U0_glFeedbackCounter_out_write;
wire    initStageInterleaveS_U0_glStageInStream_V_V_read;
wire   [1:0] initStageInterleaveS_U0_ap_return;
wire    ap_channel_done_stageOut_V;
wire    stageOut_V_full_n;
wire    rwSAEPerfectLoopStre_U0_ap_start;
wire    rwSAEPerfectLoopStre_U0_ap_done;
wire    rwSAEPerfectLoopStre_U0_ap_continue;
wire    rwSAEPerfectLoopStre_U0_ap_idle;
wire    rwSAEPerfectLoopStre_U0_ap_ready;
wire    rwSAEPerfectLoopStre_U0_xStream_V_V_read;
wire    rwSAEPerfectLoopStre_U0_yStream_V_V_read;
wire    rwSAEPerfectLoopStre_U0_tsStream_V_V_read;
wire    rwSAEPerfectLoopStre_U0_polStream_V_V_read;
wire   [639:0] rwSAEPerfectLoopStre_U0_outputDataStream_V_V_din;
wire    rwSAEPerfectLoopStre_U0_outputDataStream_V_V_write;
wire   [4:0] rwSAEPerfectLoopStre_U0_size2_V_out_din;
wire    rwSAEPerfectLoopStre_U0_size2_V_out_write;
wire   [4:0] rwSAEPerfectLoopStre_U0_ap_return;
wire    ap_channel_done_size1_V;
wire    size1_V_full_n;
wire    sortedIdxStreamV3_5_U0_ap_start;
wire    sortedIdxStreamV3_5_U0_ap_done;
wire    sortedIdxStreamV3_5_U0_ap_continue;
wire    sortedIdxStreamV3_5_U0_ap_idle;
wire    sortedIdxStreamV3_5_U0_ap_ready;
wire    sortedIdxStreamV3_5_U0_tsStream_V_V_read;
wire   [99:0] sortedIdxStreamV3_5_U0_ap_return;
wire    ap_channel_done_idxDataWide_V;
wire    idxDataWide_V_full_n;
wire    checkIdxGeneralV3_5_U0_ap_start;
wire    checkIdxGeneralV3_5_U0_ap_done;
wire    checkIdxGeneralV3_5_U0_ap_continue;
wire    checkIdxGeneralV3_5_U0_ap_idle;
wire    checkIdxGeneralV3_5_U0_ap_ready;
wire    checkIdxGeneralV3_5_U0_size2_V_read;
wire   [0:0] checkIdxGeneralV3_5_U0_ap_return;
wire    ap_channel_done_isStageCorner_V;
wire    isStageCorner_V_full_n;
wire    feedbackInterleaveSt_U0_ap_start;
wire    feedbackInterleaveSt_U0_ap_done;
wire    feedbackInterleaveSt_U0_ap_continue;
wire    feedbackInterleaveSt_U0_ap_idle;
wire    feedbackInterleaveSt_U0_ap_ready;
wire   [0:0] feedbackInterleaveSt_U0_isFinalCornerStream_V_V_din;
wire    feedbackInterleaveSt_U0_isFinalCornerStream_V_V_write;
wire    feedbackInterleaveSt_U0_glFeedbackCounter_read;
wire   [1:0] feedbackInterleaveSt_U0_glStageInStream_V_V_din;
wire    feedbackInterleaveSt_U0_glStageInStream_V_V_write;
wire    combineOutputStream_U0_ap_start;
wire    combineOutputStream_U0_ap_done;
wire    combineOutputStream_U0_ap_continue;
wire    combineOutputStream_U0_ap_idle;
wire    combineOutputStream_U0_ap_ready;
wire    combineOutputStream_U0_packetEventDataStrea_read;
wire    combineOutputStream_U0_stageCornerStream_V_s_read;
wire   [15:0] combineOutputStream_U0_xStreamOut_V_V_TDATA;
wire    combineOutputStream_U0_xStreamOut_V_V_TVALID;
wire   [15:0] combineOutputStream_U0_yStreamOut_V_V_TDATA;
wire    combineOutputStream_U0_yStreamOut_V_V_TVALID;
wire   [7:0] combineOutputStream_U0_polStreamOut_V_V_TDATA;
wire    combineOutputStream_U0_polStreamOut_V_V_TVALID;
wire   [63:0] combineOutputStream_U0_tsStreamOut_V_V_TDATA;
wire    combineOutputStream_U0_tsStreamOut_V_V_TVALID;
wire   [7:0] combineOutputStream_U0_isFinalCornerStream_s_TDATA;
wire    combineOutputStream_U0_isFinalCornerStream_s_TVALID;
wire    ap_sync_continue;
wire    xStream_V_V_full_n;
wire   [9:0] xStream_V_V_dout;
wire    xStream_V_V_empty_n;
wire    yStream_V_V_full_n;
wire   [9:0] yStream_V_V_dout;
wire    yStream_V_V_empty_n;
wire    polStream_V_V_full_n;
wire   [0:0] polStream_V_V_dout;
wire    polStream_V_V_empty_n;
wire    tsStream_V_V_full_n;
wire   [31:0] tsStream_V_V_dout;
wire    tsStream_V_V_empty_n;
wire    pktEventDataStream_V_full_n;
wire   [95:0] pktEventDataStream_V_dout;
wire    pktEventDataStream_V_empty_n;
wire    glFeedbackCounter_c_full_n;
wire   [31:0] glFeedbackCounter_c_dout;
wire    glFeedbackCounter_c_empty_n;
wire    glStageInStream_V_V_full_n;
wire   [1:0] glStageInStream_V_V_dout;
wire    glStageInStream_V_V_empty_n;
wire   [1:0] stageOut_V_dout;
wire    stageOut_V_empty_n;
wire    inStream_V_V_full_n;
wire   [639:0] inStream_V_V_dout;
wire    inStream_V_V_empty_n;
wire    size2_V_c_full_n;
wire   [4:0] size2_V_c_dout;
wire    size2_V_c_empty_n;
wire   [4:0] size1_V_dout;
wire    size1_V_empty_n;
wire   [99:0] idxDataWide_V_dout;
wire    idxDataWide_V_empty_n;
wire   [0:0] isStageCorner_V_dout;
wire    isStageCorner_V_empty_n;
wire    stageCornerStream_V_s_full_n;
wire   [0:0] stageCornerStream_V_s_dout;
wire    stageCornerStream_V_s_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_combineOutputStream_U0_din;
wire    start_for_combineOutputStream_U0_full_n;
wire   [0:0] start_for_combineOutputStream_U0_dout;
wire    start_for_combineOutputStream_U0_empty_n;
wire    initStageInterleaveS_U0_start_full_n;
wire    initStageInterleaveS_U0_start_write;
wire    rwSAEPerfectLoopStre_U0_start_full_n;
wire    rwSAEPerfectLoopStre_U0_start_write;
wire    sortedIdxStreamV3_5_U0_start_full_n;
wire    sortedIdxStreamV3_5_U0_start_write;
wire    checkIdxGeneralV3_5_U0_start_full_n;
wire    checkIdxGeneralV3_5_U0_start_write;
wire    feedbackInterleaveSt_U0_start_full_n;
wire    feedbackInterleaveSt_U0_start_write;
wire    combineOutputStream_U0_start_full_n;
wire    combineOutputStream_U0_start_write;

// power-on initialization
initial begin
#0 initStageInterleaveS_U0_ap_start = 1'b0;
end

truncateStream truncateStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(truncateStream_U0_ap_start),
    .start_full_n(start_for_combineOutputStream_U0_full_n),
    .ap_done(truncateStream_U0_ap_done),
    .ap_continue(truncateStream_U0_ap_continue),
    .ap_idle(truncateStream_U0_ap_idle),
    .ap_ready(truncateStream_U0_ap_ready),
    .packetEventDataStrea_din(truncateStream_U0_packetEventDataStrea_din),
    .packetEventDataStrea_full_n(pktEventDataStream_V_full_n),
    .packetEventDataStrea_write(truncateStream_U0_packetEventDataStrea_write),
    .xStreamOut_V_V_din(truncateStream_U0_xStreamOut_V_V_din),
    .xStreamOut_V_V_full_n(xStream_V_V_full_n),
    .xStreamOut_V_V_write(truncateStream_U0_xStreamOut_V_V_write),
    .yStreamOut_V_V_din(truncateStream_U0_yStreamOut_V_V_din),
    .yStreamOut_V_V_full_n(yStream_V_V_full_n),
    .yStreamOut_V_V_write(truncateStream_U0_yStreamOut_V_V_write),
    .polStreamOut_V_V_din(truncateStream_U0_polStreamOut_V_V_din),
    .polStreamOut_V_V_full_n(polStream_V_V_full_n),
    .polStreamOut_V_V_write(truncateStream_U0_polStreamOut_V_V_write),
    .tsStreamOut_V_V_din(truncateStream_U0_tsStreamOut_V_V_din),
    .tsStreamOut_V_V_full_n(tsStream_V_V_full_n),
    .tsStreamOut_V_V_write(truncateStream_U0_tsStreamOut_V_V_write),
    .start_out(truncateStream_U0_start_out),
    .start_write(truncateStream_U0_start_write),
    .xStreamIn_V_V_TDATA(xStreamIn_V_V_TDATA),
    .xStreamIn_V_V_TVALID(xStreamIn_V_V_TVALID),
    .xStreamIn_V_V_TREADY(truncateStream_U0_xStreamIn_V_V_TREADY),
    .yStreamIn_V_V_TDATA(yStreamIn_V_V_TDATA),
    .yStreamIn_V_V_TVALID(yStreamIn_V_V_TVALID),
    .yStreamIn_V_V_TREADY(truncateStream_U0_yStreamIn_V_V_TREADY),
    .polStreamIn_V_V_TDATA(polStreamIn_V_V_TDATA),
    .polStreamIn_V_V_TVALID(polStreamIn_V_V_TVALID),
    .polStreamIn_V_V_TREADY(truncateStream_U0_polStreamIn_V_V_TREADY),
    .tsStreamIn_V_V_TDATA(tsStreamIn_V_V_TDATA),
    .tsStreamIn_V_V_TVALID(tsStreamIn_V_V_TVALID),
    .tsStreamIn_V_V_TREADY(truncateStream_U0_tsStreamIn_V_V_TREADY)
);

initStageInterleaveS initStageInterleaveS_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(initStageInterleaveS_U0_ap_start),
    .ap_done(initStageInterleaveS_U0_ap_done),
    .ap_continue(initStageInterleaveS_U0_ap_continue),
    .ap_idle(initStageInterleaveS_U0_ap_idle),
    .ap_ready(initStageInterleaveS_U0_ap_ready),
    .glFeedbackCounter_out_din(initStageInterleaveS_U0_glFeedbackCounter_out_din),
    .glFeedbackCounter_out_full_n(glFeedbackCounter_c_full_n),
    .glFeedbackCounter_out_write(initStageInterleaveS_U0_glFeedbackCounter_out_write),
    .glStageInStream_V_V_dout(glStageInStream_V_V_dout),
    .glStageInStream_V_V_empty_n(glStageInStream_V_V_empty_n),
    .glStageInStream_V_V_read(initStageInterleaveS_U0_glStageInStream_V_V_read),
    .ap_return(initStageInterleaveS_U0_ap_return)
);

rwSAEPerfectLoopStre rwSAEPerfectLoopStre_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(rwSAEPerfectLoopStre_U0_ap_start),
    .ap_done(rwSAEPerfectLoopStre_U0_ap_done),
    .ap_continue(rwSAEPerfectLoopStre_U0_ap_continue),
    .ap_idle(rwSAEPerfectLoopStre_U0_ap_idle),
    .ap_ready(rwSAEPerfectLoopStre_U0_ap_ready),
    .xStream_V_V_dout(xStream_V_V_dout),
    .xStream_V_V_empty_n(xStream_V_V_empty_n),
    .xStream_V_V_read(rwSAEPerfectLoopStre_U0_xStream_V_V_read),
    .yStream_V_V_dout(yStream_V_V_dout),
    .yStream_V_V_empty_n(yStream_V_V_empty_n),
    .yStream_V_V_read(rwSAEPerfectLoopStre_U0_yStream_V_V_read),
    .tsStream_V_V_dout(tsStream_V_V_dout),
    .tsStream_V_V_empty_n(tsStream_V_V_empty_n),
    .tsStream_V_V_read(rwSAEPerfectLoopStre_U0_tsStream_V_V_read),
    .polStream_V_V_dout(polStream_V_V_dout),
    .polStream_V_V_empty_n(polStream_V_V_empty_n),
    .polStream_V_V_read(rwSAEPerfectLoopStre_U0_polStream_V_V_read),
    .outputDataStream_V_V_din(rwSAEPerfectLoopStre_U0_outputDataStream_V_V_din),
    .outputDataStream_V_V_full_n(inStream_V_V_full_n),
    .outputDataStream_V_V_write(rwSAEPerfectLoopStre_U0_outputDataStream_V_V_write),
    .size2_V_out_din(rwSAEPerfectLoopStre_U0_size2_V_out_din),
    .size2_V_out_full_n(size2_V_c_full_n),
    .size2_V_out_write(rwSAEPerfectLoopStre_U0_size2_V_out_write),
    .p_read(stageOut_V_dout),
    .ap_return(rwSAEPerfectLoopStre_U0_ap_return)
);

sortedIdxStreamV3_5_s sortedIdxStreamV3_5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sortedIdxStreamV3_5_U0_ap_start),
    .ap_done(sortedIdxStreamV3_5_U0_ap_done),
    .ap_continue(sortedIdxStreamV3_5_U0_ap_continue),
    .ap_idle(sortedIdxStreamV3_5_U0_ap_idle),
    .ap_ready(sortedIdxStreamV3_5_U0_ap_ready),
    .tsStream_V_V_dout(inStream_V_V_dout),
    .tsStream_V_V_empty_n(inStream_V_V_empty_n),
    .tsStream_V_V_read(sortedIdxStreamV3_5_U0_tsStream_V_V_read),
    .p_read(size1_V_dout),
    .ap_return(sortedIdxStreamV3_5_U0_ap_return)
);

checkIdxGeneralV3_5_s checkIdxGeneralV3_5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(checkIdxGeneralV3_5_U0_ap_start),
    .ap_done(checkIdxGeneralV3_5_U0_ap_done),
    .ap_continue(checkIdxGeneralV3_5_U0_ap_continue),
    .ap_idle(checkIdxGeneralV3_5_U0_ap_idle),
    .ap_ready(checkIdxGeneralV3_5_U0_ap_ready),
    .size2_V_dout(size2_V_c_dout),
    .size2_V_empty_n(size2_V_c_empty_n),
    .size2_V_read(checkIdxGeneralV3_5_U0_size2_V_read),
    .p_read(idxDataWide_V_dout),
    .ap_return(checkIdxGeneralV3_5_U0_ap_return)
);

feedbackInterleaveSt feedbackInterleaveSt_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(feedbackInterleaveSt_U0_ap_start),
    .ap_done(feedbackInterleaveSt_U0_ap_done),
    .ap_continue(feedbackInterleaveSt_U0_ap_continue),
    .ap_idle(feedbackInterleaveSt_U0_ap_idle),
    .ap_ready(feedbackInterleaveSt_U0_ap_ready),
    .p_read(isStageCorner_V_dout),
    .isFinalCornerStream_V_V_din(feedbackInterleaveSt_U0_isFinalCornerStream_V_V_din),
    .isFinalCornerStream_V_V_full_n(stageCornerStream_V_s_full_n),
    .isFinalCornerStream_V_V_write(feedbackInterleaveSt_U0_isFinalCornerStream_V_V_write),
    .glFeedbackCounter_dout(glFeedbackCounter_c_dout),
    .glFeedbackCounter_empty_n(glFeedbackCounter_c_empty_n),
    .glFeedbackCounter_read(feedbackInterleaveSt_U0_glFeedbackCounter_read),
    .glStageInStream_V_V_din(feedbackInterleaveSt_U0_glStageInStream_V_V_din),
    .glStageInStream_V_V_full_n(glStageInStream_V_V_full_n),
    .glStageInStream_V_V_write(feedbackInterleaveSt_U0_glStageInStream_V_V_write)
);

combineOutputStream combineOutputStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(combineOutputStream_U0_ap_start),
    .ap_done(combineOutputStream_U0_ap_done),
    .ap_continue(combineOutputStream_U0_ap_continue),
    .ap_idle(combineOutputStream_U0_ap_idle),
    .ap_ready(combineOutputStream_U0_ap_ready),
    .packetEventDataStrea_dout(pktEventDataStream_V_dout),
    .packetEventDataStrea_empty_n(pktEventDataStream_V_empty_n),
    .packetEventDataStrea_read(combineOutputStream_U0_packetEventDataStrea_read),
    .stageCornerStream_V_s_dout(stageCornerStream_V_s_dout),
    .stageCornerStream_V_s_empty_n(stageCornerStream_V_s_empty_n),
    .stageCornerStream_V_s_read(combineOutputStream_U0_stageCornerStream_V_s_read),
    .xStreamOut_V_V_TREADY(xStreamOut_V_V_TREADY),
    .yStreamOut_V_V_TREADY(yStreamOut_V_V_TREADY),
    .polStreamOut_V_V_TREADY(polStreamOut_V_V_TREADY),
    .tsStreamOut_V_V_TREADY(tsStreamOut_V_V_TREADY),
    .isFinalCornerStream_s_TREADY(isFinalCornerStream_V_V_TREADY),
    .xStreamOut_V_V_TDATA(combineOutputStream_U0_xStreamOut_V_V_TDATA),
    .xStreamOut_V_V_TVALID(combineOutputStream_U0_xStreamOut_V_V_TVALID),
    .yStreamOut_V_V_TDATA(combineOutputStream_U0_yStreamOut_V_V_TDATA),
    .yStreamOut_V_V_TVALID(combineOutputStream_U0_yStreamOut_V_V_TVALID),
    .polStreamOut_V_V_TDATA(combineOutputStream_U0_polStreamOut_V_V_TDATA),
    .polStreamOut_V_V_TVALID(combineOutputStream_U0_polStreamOut_V_V_TVALID),
    .tsStreamOut_V_V_TDATA(combineOutputStream_U0_tsStreamOut_V_V_TDATA),
    .tsStreamOut_V_V_TVALID(combineOutputStream_U0_tsStreamOut_V_V_TVALID),
    .isFinalCornerStream_s_TDATA(combineOutputStream_U0_isFinalCornerStream_s_TDATA),
    .isFinalCornerStream_s_TVALID(combineOutputStream_U0_isFinalCornerStream_s_TVALID)
);

fifo_w10_d2_S xStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(truncateStream_U0_xStreamOut_V_V_din),
    .if_full_n(xStream_V_V_full_n),
    .if_write(truncateStream_U0_xStreamOut_V_V_write),
    .if_dout(xStream_V_V_dout),
    .if_empty_n(xStream_V_V_empty_n),
    .if_read(rwSAEPerfectLoopStre_U0_xStream_V_V_read)
);

fifo_w10_d2_S yStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(truncateStream_U0_yStreamOut_V_V_din),
    .if_full_n(yStream_V_V_full_n),
    .if_write(truncateStream_U0_yStreamOut_V_V_write),
    .if_dout(yStream_V_V_dout),
    .if_empty_n(yStream_V_V_empty_n),
    .if_read(rwSAEPerfectLoopStre_U0_yStream_V_V_read)
);

fifo_w1_d2_S polStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(truncateStream_U0_polStreamOut_V_V_din),
    .if_full_n(polStream_V_V_full_n),
    .if_write(truncateStream_U0_polStreamOut_V_V_write),
    .if_dout(polStream_V_V_dout),
    .if_empty_n(polStream_V_V_empty_n),
    .if_read(rwSAEPerfectLoopStre_U0_polStream_V_V_read)
);

fifo_w32_d2_S tsStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(truncateStream_U0_tsStreamOut_V_V_din),
    .if_full_n(tsStream_V_V_full_n),
    .if_write(truncateStream_U0_tsStreamOut_V_V_write),
    .if_dout(tsStream_V_V_dout),
    .if_empty_n(tsStream_V_V_empty_n),
    .if_read(rwSAEPerfectLoopStre_U0_tsStream_V_V_read)
);

fifo_w96_d10_S pktEventDataStream_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(truncateStream_U0_packetEventDataStrea_din),
    .if_full_n(pktEventDataStream_V_full_n),
    .if_write(truncateStream_U0_packetEventDataStrea_write),
    .if_dout(pktEventDataStream_V_dout),
    .if_empty_n(pktEventDataStream_V_empty_n),
    .if_read(combineOutputStream_U0_packetEventDataStrea_read)
);

fifo_w32_d5_A glFeedbackCounter_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(initStageInterleaveS_U0_glFeedbackCounter_out_din),
    .if_full_n(glFeedbackCounter_c_full_n),
    .if_write(initStageInterleaveS_U0_glFeedbackCounter_out_write),
    .if_dout(glFeedbackCounter_c_dout),
    .if_empty_n(glFeedbackCounter_c_empty_n),
    .if_read(feedbackInterleaveSt_U0_glFeedbackCounter_read)
);

fifo_w2_d10_A glStageInStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(feedbackInterleaveSt_U0_glStageInStream_V_V_din),
    .if_full_n(glStageInStream_V_V_full_n),
    .if_write(feedbackInterleaveSt_U0_glStageInStream_V_V_write),
    .if_dout(glStageInStream_V_V_dout),
    .if_empty_n(glStageInStream_V_V_empty_n),
    .if_read(initStageInterleaveS_U0_glStageInStream_V_V_read)
);

fifo_w2_d2_A stageOut_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(initStageInterleaveS_U0_ap_return),
    .if_full_n(stageOut_V_full_n),
    .if_write(initStageInterleaveS_U0_ap_done),
    .if_dout(stageOut_V_dout),
    .if_empty_n(stageOut_V_empty_n),
    .if_read(rwSAEPerfectLoopStre_U0_ap_ready)
);

fifo_w640_d10_S inStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(rwSAEPerfectLoopStre_U0_outputDataStream_V_V_din),
    .if_full_n(inStream_V_V_full_n),
    .if_write(rwSAEPerfectLoopStre_U0_outputDataStream_V_V_write),
    .if_dout(inStream_V_V_dout),
    .if_empty_n(inStream_V_V_empty_n),
    .if_read(sortedIdxStreamV3_5_U0_tsStream_V_V_read)
);

fifo_w5_d3_A size2_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(rwSAEPerfectLoopStre_U0_size2_V_out_din),
    .if_full_n(size2_V_c_full_n),
    .if_write(rwSAEPerfectLoopStre_U0_size2_V_out_write),
    .if_dout(size2_V_c_dout),
    .if_empty_n(size2_V_c_empty_n),
    .if_read(checkIdxGeneralV3_5_U0_size2_V_read)
);

fifo_w5_d2_A size1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(rwSAEPerfectLoopStre_U0_ap_return),
    .if_full_n(size1_V_full_n),
    .if_write(rwSAEPerfectLoopStre_U0_ap_done),
    .if_dout(size1_V_dout),
    .if_empty_n(size1_V_empty_n),
    .if_read(sortedIdxStreamV3_5_U0_ap_ready)
);

fifo_w100_d2_A idxDataWide_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sortedIdxStreamV3_5_U0_ap_return),
    .if_full_n(idxDataWide_V_full_n),
    .if_write(sortedIdxStreamV3_5_U0_ap_done),
    .if_dout(idxDataWide_V_dout),
    .if_empty_n(idxDataWide_V_empty_n),
    .if_read(checkIdxGeneralV3_5_U0_ap_ready)
);

fifo_w1_d2_A isStageCorner_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(checkIdxGeneralV3_5_U0_ap_return),
    .if_full_n(isStageCorner_V_full_n),
    .if_write(checkIdxGeneralV3_5_U0_ap_done),
    .if_dout(isStageCorner_V_dout),
    .if_empty_n(isStageCorner_V_empty_n),
    .if_read(feedbackInterleaveSt_U0_ap_ready)
);

fifo_w1_d2_A stageCornerStream_V_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(feedbackInterleaveSt_U0_isFinalCornerStream_V_V_din),
    .if_full_n(stageCornerStream_V_s_full_n),
    .if_write(feedbackInterleaveSt_U0_isFinalCornerStream_V_V_write),
    .if_dout(stageCornerStream_V_s_dout),
    .if_empty_n(stageCornerStream_V_s_empty_n),
    .if_read(combineOutputStream_U0_stageCornerStream_V_s_read)
);

start_for_combineeOg start_for_combineeOg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_combineOutputStream_U0_din),
    .if_full_n(start_for_combineOutputStream_U0_full_n),
    .if_write(truncateStream_U0_start_write),
    .if_dout(start_for_combineOutputStream_U0_dout),
    .if_empty_n(start_for_combineOutputStream_U0_empty_n),
    .if_read(combineOutputStream_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        initStageInterleaveS_U0_ap_start <= 1'b0;
    end else begin
        initStageInterleaveS_U0_ap_start <= 1'b1;
    end
end

assign ap_channel_done_idxDataWide_V = sortedIdxStreamV3_5_U0_ap_done;

assign ap_channel_done_isStageCorner_V = checkIdxGeneralV3_5_U0_ap_done;

assign ap_channel_done_size1_V = rwSAEPerfectLoopStre_U0_ap_done;

assign ap_channel_done_stageOut_V = initStageInterleaveS_U0_ap_done;

assign ap_done = combineOutputStream_U0_ap_done;

assign ap_idle = (truncateStream_U0_ap_idle & sortedIdxStreamV3_5_U0_ap_idle & rwSAEPerfectLoopStre_U0_ap_idle & initStageInterleaveS_U0_ap_idle & feedbackInterleaveSt_U0_ap_idle & (isStageCorner_V_empty_n ^ 1'b1) & (idxDataWide_V_empty_n ^ 1'b1) & (size1_V_empty_n ^ 1'b1) & (stageOut_V_empty_n ^ 1'b1) & combineOutputStream_U0_ap_idle & checkIdxGeneralV3_5_U0_ap_idle);

assign ap_ready = truncateStream_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = combineOutputStream_U0_ap_done;

assign ap_sync_ready = truncateStream_U0_ap_ready;

assign checkIdxGeneralV3_5_U0_ap_continue = isStageCorner_V_full_n;

assign checkIdxGeneralV3_5_U0_ap_start = idxDataWide_V_empty_n;

assign checkIdxGeneralV3_5_U0_start_full_n = 1'b1;

assign checkIdxGeneralV3_5_U0_start_write = 1'b0;

assign combineOutputStream_U0_ap_continue = 1'b1;

assign combineOutputStream_U0_ap_start = start_for_combineOutputStream_U0_empty_n;

assign combineOutputStream_U0_start_full_n = 1'b1;

assign combineOutputStream_U0_start_write = 1'b0;

assign feedbackInterleaveSt_U0_ap_continue = 1'b1;

assign feedbackInterleaveSt_U0_ap_start = isStageCorner_V_empty_n;

assign feedbackInterleaveSt_U0_start_full_n = 1'b1;

assign feedbackInterleaveSt_U0_start_write = 1'b0;

assign initStageInterleaveS_U0_ap_continue = stageOut_V_full_n;

assign initStageInterleaveS_U0_start_full_n = 1'b1;

assign initStageInterleaveS_U0_start_write = 1'b0;

assign isFinalCornerStream_V_V_TDATA = combineOutputStream_U0_isFinalCornerStream_s_TDATA;

assign isFinalCornerStream_V_V_TVALID = combineOutputStream_U0_isFinalCornerStream_s_TVALID;

assign polStreamIn_V_V_TREADY = truncateStream_U0_polStreamIn_V_V_TREADY;

assign polStreamOut_V_V_TDATA = combineOutputStream_U0_polStreamOut_V_V_TDATA;

assign polStreamOut_V_V_TVALID = combineOutputStream_U0_polStreamOut_V_V_TVALID;

assign rwSAEPerfectLoopStre_U0_ap_continue = size1_V_full_n;

assign rwSAEPerfectLoopStre_U0_ap_start = stageOut_V_empty_n;

assign rwSAEPerfectLoopStre_U0_start_full_n = 1'b1;

assign rwSAEPerfectLoopStre_U0_start_write = 1'b0;

assign sortedIdxStreamV3_5_U0_ap_continue = idxDataWide_V_full_n;

assign sortedIdxStreamV3_5_U0_ap_start = size1_V_empty_n;

assign sortedIdxStreamV3_5_U0_start_full_n = 1'b1;

assign sortedIdxStreamV3_5_U0_start_write = 1'b0;

assign start_for_combineOutputStream_U0_din = 1'b1;

assign truncateStream_U0_ap_continue = 1'b1;

assign truncateStream_U0_ap_start = ap_start;

assign tsStreamIn_V_V_TREADY = truncateStream_U0_tsStreamIn_V_V_TREADY;

assign tsStreamOut_V_V_TDATA = combineOutputStream_U0_tsStreamOut_V_V_TDATA;

assign tsStreamOut_V_V_TVALID = combineOutputStream_U0_tsStreamOut_V_V_TVALID;

assign xStreamIn_V_V_TREADY = truncateStream_U0_xStreamIn_V_V_TREADY;

assign xStreamOut_V_V_TDATA = combineOutputStream_U0_xStreamOut_V_V_TDATA;

assign xStreamOut_V_V_TVALID = combineOutputStream_U0_xStreamOut_V_V_TVALID;

assign yStreamIn_V_V_TREADY = truncateStream_U0_yStreamIn_V_V_TREADY;

assign yStreamOut_V_V_TDATA = combineOutputStream_U0_yStreamOut_V_V_TDATA;

assign yStreamOut_V_V_TVALID = combineOutputStream_U0_yStreamOut_V_V_TVALID;

endmodule //EFAST_process_data
