#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[6]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[7]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[9]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[4]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[5]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[8]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[10]}]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERAck_SBO]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERReq_ABI]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERReset_SBO]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/U0/DVSAERAck_SBO]

#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/U0/dvsAerFifo/AlmostEmptyReg_S]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[0]}]

#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlIn_S[WriteSide][Write_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[WriteSide][AlmostFull_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/FIFOState_S[Empty_S]}]

#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[ReadSide][AlmostEmpty_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[ReadSide][Empty_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/FifoControl_SO[WriteSide][AlmostFull_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/State_DP_reg[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/State_DP_reg[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/readSideOutputDelayReg/State_DP_reg[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/readSideOutputDelayReg/State_DP_reg[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[4]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[4]}]


#set_max_delay -datapath_only -from [get_ports ulpi_dir_i_0] -to [get_pins brd_i/ulpi_wrapper_0/U0/ulpi_dir_q_reg/D] 6.000
#set_max_delay -datapath_only -from [get_ports ulpi_dir_i_0] -to [get_pins {brd_i/system_ila_2/U0/ila_lib/U0/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[16].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}] 8.480
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets ulpi_clk60_i_0_IBUF_BUFG]
