-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity initStageInterleaveS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    glFeedbackCounter_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    glFeedbackCounter_out_full_n : IN STD_LOGIC;
    glFeedbackCounter_out_write : OUT STD_LOGIC;
    glStageInStream_V_V_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    glStageInStream_V_V_empty_n : IN STD_LOGIC;
    glStageInStream_V_V_read : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of initStageInterleaveS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal glInitCounter : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal glFeedbackCounter_out_blk_n : STD_LOGIC;
    signal glStageInStream_V_V_blk_n : STD_LOGIC;
    signal tmp_fu_57_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_27_i_i_fu_65_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv2_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_preg <= ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                glInitCounter <= tmp_27_i_i_fu_65_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4_assign_proc : process(ap_CS_fsm_state1, glStageInStream_V_V_dout, tmp_fu_57_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((tmp_fu_57_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4 <= ap_const_lv2_0;
            elsif ((tmp_fu_57_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4 <= glStageInStream_V_V_dout;
            else 
                ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4 <= "XX";
            end if;
        else 
            ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4 <= "XX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3, ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4, ap_return_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return <= ap_phi_mux_stageOutStream_V_wri_phi_fu_44_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    glFeedbackCounter_out_blk_n_assign_proc : process(ap_CS_fsm_state1, glFeedbackCounter_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            glFeedbackCounter_out_blk_n <= glFeedbackCounter_out_full_n;
        else 
            glFeedbackCounter_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    glFeedbackCounter_out_din <= glInitCounter;

    glFeedbackCounter_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            glFeedbackCounter_out_write <= ap_const_logic_1;
        else 
            glFeedbackCounter_out_write <= ap_const_logic_0;
        end if; 
    end process;


    glStageInStream_V_V_blk_n_assign_proc : process(ap_CS_fsm_state1, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        if (((tmp_fu_57_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            glStageInStream_V_V_blk_n <= glStageInStream_V_V_empty_n;
        else 
            glStageInStream_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    glStageInStream_V_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, glFeedbackCounter_out_full_n, glStageInStream_V_V_empty_n, tmp_fu_57_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (glFeedbackCounter_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_fu_57_p3 = ap_const_lv1_1) and (glStageInStream_V_V_empty_n = ap_const_logic_0)))) and (tmp_fu_57_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            glStageInStream_V_V_read <= ap_const_logic_1;
        else 
            glStageInStream_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_27_i_i_fu_65_p2 <= std_logic_vector(unsigned(glInitCounter) + unsigned(ap_const_lv32_1));
    tmp_fu_57_p3 <= glInitCounter(1 downto 1);
end behav;
